# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:appletvos)

platform :appletvos do
  desc "Push a new beta build to TestFlight"
  lane :prod do
    increment_build_number(xcodeproj: "artblock.xcodeproj")
    build_app(workspace: "artblock.xcworkspace", scheme: "artblock")
    upload_to_testflight
  end
end
